# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 17:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20160702_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 2, 17, 52, 3, 576564, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
